[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    knolleary/PubSubClient@2.8
    adafruit/DHT sensor library@1.4.6
    adafruit/Adafruit Unified Sensor@1.1.14
